package ua.divas.service.app.common.serviceinterface;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;

import ua.divas.service.vo.common.ContactDetailsViewSDO;
import ua.divas.service.vo.common.CurrencyViewSDO;
import ua.divas.service.vo.common.DivisionSotrViewSDO;
import ua.divas.service.vo.common.DivisionsViewSDO;
import ua.divas.service.vo.common.FirmsViewSDO;
import ua.divas.service.vo.common.GroupmembersViewSDO;
import ua.divas.service.vo.common.KassaSettingsViewSDO;
import ua.divas.service.vo.common.KassaViewSDO;
import ua.divas.service.vo.common.KontragentsViewSDO;
import ua.divas.service.vo.common.LastPricesViewSDO;
import ua.divas.service.vo.common.MeasureUnitViewSDO;
import ua.divas.service.vo.common.NomGroupSDO;
import ua.divas.service.vo.common.NomenklaturaViewSDO;
import ua.divas.service.vo.common.OperationPkoViewSDO;
import ua.divas.service.vo.common.OperationRkoViewSDO;
import ua.divas.service.vo.common.OrderStatusViewSDO;
import ua.divas.service.vo.common.OrdersTpOplatyViewSDO;
import ua.divas.service.vo.common.OrdersTpUslugiViewSDO;
import ua.divas.service.vo.common.OrdersViewSDO;
import ua.divas.service.vo.common.UserSettingsViewSDO;
import ua.divas.service.vo.common.UsersViewSDO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 25 18:37:08 EEST 2015
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/ua/divas/service/app/common/", name = "DivasService",
                    wsdlLocation = "ua/divas/service/app/common/serviceinterface/DivasService.wsdl")
@SDODatabinding(schemaLocation = "ua/divas/service/app/common/serviceinterface/DivasService.xsd")
public interface DivasService {


    public static final String NAME = "{/ua/divas/service/app/common/}DivasService";

    @WebMethod(action = "/ua/divas/service/app/common/getContactDetailsView1", operationName = "getContactDetailsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getContactDetailsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getContactDetailsView1Response")
    @WebResult(name = "result")
    ContactDetailsViewSDO getContactDetailsView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                                 String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/updateContactDetailsView1",
               operationName = "updateContactDetailsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateContactDetailsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "updateContactDetailsView1Response")
    @WebResult(name = "result")
    ContactDetailsViewSDO updateContactDetailsView1(@WebParam(mode = WebParam.Mode.IN, name = "contactDetailsView1")
                                                    ContactDetailsViewSDO contactDetailsView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findContactDetailsView1",
               operationName = "findContactDetailsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findContactDetailsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findContactDetailsView1Response")
    @WebResult(name = "result")
    List<ContactDetailsViewSDO> findContactDetailsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                        FindCriteria findCriteria,
                                                        @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                        FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getCurrencyView1", operationName = "getCurrencyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getCurrencyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getCurrencyView1Response")
    @WebResult(name = "result")
    CurrencyViewSDO getCurrencyView1(@WebParam(mode = WebParam.Mode.IN, name = "id") String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findCurrencyView1", operationName = "findCurrencyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findCurrencyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findCurrencyView1Response")
    @WebResult(name = "result")
    List<CurrencyViewSDO> findCurrencyView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                            FindCriteria findCriteria,
                                            @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                            FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getDivisionSotrView1", operationName = "getDivisionSotrView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getDivisionSotrView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getDivisionSotrView1Response")
    @WebResult(name = "result")
    DivisionSotrViewSDO getDivisionSotrView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                             String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findDivisionSotrView1", operationName = "findDivisionSotrView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findDivisionSotrView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findDivisionSotrView1Response")
    @WebResult(name = "result")
    List<DivisionSotrViewSDO> findDivisionSotrView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getDivisionsView1", operationName = "getDivisionsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getDivisionsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getDivisionsView1Response")
    @WebResult(name = "result")
    DivisionsViewSDO getDivisionsView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                       String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findDivisionsView1", operationName = "findDivisionsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findDivisionsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findDivisionsView1Response")
    @WebResult(name = "result")
    List<DivisionsViewSDO> findDivisionsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                              FindCriteria findCriteria,
                                              @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                              FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getFirmsView1", operationName = "getFirmsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getFirmsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getFirmsView1Response")
    @WebResult(name = "result")
    FirmsViewSDO getFirmsView1(@WebParam(mode = WebParam.Mode.IN, name = "id") String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findFirmsView1", operationName = "findFirmsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findFirmsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findFirmsView1Response")
    @WebResult(name = "result")
    List<FirmsViewSDO> findFirmsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                      FindCriteria findCriteria,
                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                      FindControl findControl) throws ServiceException;


    @WebMethod(action = "/ua/divas/service/app/common/findKassaSettingsView1", operationName = "findKassaSettingsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findKassaSettingsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findKassaSettingsView1Response")
    @WebResult(name = "result")
    List<KassaSettingsViewSDO> findKassaSettingsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                      FindCriteria findCriteria,
                                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                      FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getKassaView1", operationName = "getKassaView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getKassaView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getKassaView1Response")
    @WebResult(name = "result")
    KassaViewSDO getKassaView1(@WebParam(mode = WebParam.Mode.IN, name = "id") String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findKassaView1", operationName = "findKassaView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findKassaView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findKassaView1Response")
    @WebResult(name = "result")
    List<KassaViewSDO> findKassaView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                      FindCriteria findCriteria,
                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                      FindControl findControl) throws ServiceException;


    @WebMethod(action = "/ua/divas/service/app/common/updateKontragentsView1", operationName = "updateKontragentsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateKontragentsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "updateKontragentsView1Response")
    @WebResult(name = "result")
    KontragentsViewSDO updateKontragentsView1(@WebParam(mode = WebParam.Mode.IN, name = "kontragentsView1")
                                              KontragentsViewSDO kontragentsView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findKontragentsView1", operationName = "findKontragentsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findKontragentsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findKontragentsView1Response")
    @WebResult(name = "result")
    List<KontragentsViewSDO> findKontragentsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                  FindCriteria findCriteria,
                                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getLastPricesView1", operationName = "getLastPricesView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getLastPricesView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getLastPricesView1Response")
    @WebResult(name = "result")
    LastPricesViewSDO getLastPricesView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                         String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findLastPricesView1", operationName = "findLastPricesView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findLastPricesView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findLastPricesView1Response")
    @WebResult(name = "result")
    List<LastPricesViewSDO> findLastPricesView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                FindCriteria findCriteria,
                                                @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getMeasureUnitView1", operationName = "getMeasureUnitView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getMeasureUnitView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getMeasureUnitView1Response")
    @WebResult(name = "result")
    MeasureUnitViewSDO getMeasureUnitView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                           String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findMeasureUnitView1", operationName = "findMeasureUnitView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findMeasureUnitView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findMeasureUnitView1Response")
    @WebResult(name = "result")
    List<MeasureUnitViewSDO> findMeasureUnitView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                  FindCriteria findCriteria,
                                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getOperationPkoView1", operationName = "getOperationPkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOperationPkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getOperationPkoView1Response")
    @WebResult(name = "result")
    OperationPkoViewSDO getOperationPkoView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                             String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findOperationPkoView1", operationName = "findOperationPkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findOperationPkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findOperationPkoView1Response")
    @WebResult(name = "result")
    List<OperationPkoViewSDO> findOperationPkoView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getOperationRkoView1", operationName = "getOperationRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOperationRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getOperationRkoView1Response")
    @WebResult(name = "result")
    OperationRkoViewSDO getOperationRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                             String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findOperationRkoView1", operationName = "findOperationRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findOperationRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findOperationRkoView1Response")
    @WebResult(name = "result")
    List<OperationRkoViewSDO> findOperationRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;


    @WebMethod(action = "/ua/divas/service/app/common/findOrderStatusView1", operationName = "findOrderStatusView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findOrderStatusView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findOrderStatusView1Response")
    @WebResult(name = "result")
    List<OrderStatusViewSDO> findOrderStatusView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                  FindCriteria findCriteria,
                                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getOrdersTpOplatyView1", operationName = "getOrdersTpOplatyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOrdersTpOplatyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getOrdersTpOplatyView1Response")
    @WebResult(name = "result")
    OrdersTpOplatyViewSDO getOrdersTpOplatyView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                                 String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/createOrdersTpOplatyView1",
               operationName = "createOrdersTpOplatyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createOrdersTpOplatyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "createOrdersTpOplatyView1Response")
    @WebResult(name = "result")
    OrdersTpOplatyViewSDO createOrdersTpOplatyView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpOplatyView1")
                                                    OrdersTpOplatyViewSDO ordersTpOplatyView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/updateOrdersTpOplatyView1",
               operationName = "updateOrdersTpOplatyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateOrdersTpOplatyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "updateOrdersTpOplatyView1Response")
    @WebResult(name = "result")
    OrdersTpOplatyViewSDO updateOrdersTpOplatyView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpOplatyView1")
                                                    OrdersTpOplatyViewSDO ordersTpOplatyView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/deleteOrdersTpOplatyView1",
               operationName = "deleteOrdersTpOplatyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "deleteOrdersTpOplatyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "deleteOrdersTpOplatyView1Response")
    void deleteOrdersTpOplatyView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpOplatyView1")
                                   OrdersTpOplatyViewSDO ordersTpOplatyView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/mergeOrdersTpOplatyView1",
               operationName = "mergeOrdersTpOplatyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergeOrdersTpOplatyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "mergeOrdersTpOplatyView1Response")
    @WebResult(name = "result")
    OrdersTpOplatyViewSDO mergeOrdersTpOplatyView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpOplatyView1")
                                                   OrdersTpOplatyViewSDO ordersTpOplatyView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findOrdersTpOplatyView1",
               operationName = "findOrdersTpOplatyView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findOrdersTpOplatyView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findOrdersTpOplatyView1Response")
    @WebResult(name = "result")
    List<OrdersTpOplatyViewSDO> findOrdersTpOplatyView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                        FindCriteria findCriteria,
                                                        @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                        FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getOrdersTpUslugiView1", operationName = "getOrdersTpUslugiView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOrdersTpUslugiView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getOrdersTpUslugiView1Response")
    @WebResult(name = "result")
    OrdersTpUslugiViewSDO getOrdersTpUslugiView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                                 String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/createOrdersTpUslugiView1",
               operationName = "createOrdersTpUslugiView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createOrdersTpUslugiView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "createOrdersTpUslugiView1Response")
    @WebResult(name = "result")
    OrdersTpUslugiViewSDO createOrdersTpUslugiView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpUslugiView1")
                                                    OrdersTpUslugiViewSDO ordersTpUslugiView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/updateOrdersTpUslugiView1",
               operationName = "updateOrdersTpUslugiView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateOrdersTpUslugiView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "updateOrdersTpUslugiView1Response")
    @WebResult(name = "result")
    OrdersTpUslugiViewSDO updateOrdersTpUslugiView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpUslugiView1")
                                                    OrdersTpUslugiViewSDO ordersTpUslugiView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/deleteOrdersTpUslugiView1",
               operationName = "deleteOrdersTpUslugiView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "deleteOrdersTpUslugiView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "deleteOrdersTpUslugiView1Response")
    void deleteOrdersTpUslugiView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpUslugiView1")
                                   OrdersTpUslugiViewSDO ordersTpUslugiView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/mergeOrdersTpUslugiView1",
               operationName = "mergeOrdersTpUslugiView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergeOrdersTpUslugiView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "mergeOrdersTpUslugiView1Response")
    @WebResult(name = "result")
    OrdersTpUslugiViewSDO mergeOrdersTpUslugiView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersTpUslugiView1")
                                                   OrdersTpUslugiViewSDO ordersTpUslugiView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findOrdersTpUslugiView1",
               operationName = "findOrdersTpUslugiView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findOrdersTpUslugiView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findOrdersTpUslugiView1Response")
    @WebResult(name = "result")
    List<OrdersTpUslugiViewSDO> findOrdersTpUslugiView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                        FindCriteria findCriteria,
                                                        @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                        FindControl findControl) throws ServiceException;


    @WebMethod(action = "/ua/divas/service/app/common/updateOrdersView1", operationName = "updateOrdersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateOrdersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateOrdersView1Response")
    @WebResult(name = "result")
    OrdersViewSDO updateOrdersView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersView1")
                                    OrdersViewSDO ordersView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/mergeOrdersView1", operationName = "mergeOrdersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergeOrdersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergeOrdersView1Response")
    @WebResult(name = "result")
    OrdersViewSDO mergeOrdersView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersView1")
                                   OrdersViewSDO ordersView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findOrdersView1", operationName = "findOrdersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findOrdersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findOrdersView1Response")
    @WebResult(name = "result")
    List<OrdersViewSDO> findOrdersView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                        FindCriteria findCriteria,
                                        @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                        FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getPkoView1", operationName = "getPkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getPkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getPkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.PkoViewSDO getPkoView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                                      String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/createPkoView1", operationName = "createPkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createPkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createPkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.PkoViewSDO createPkoView1(@WebParam(mode = WebParam.Mode.IN, name = "pkoView1")
                                                         ua.divas.service.vo.common.PkoViewSDO pkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/updatePkoView1", operationName = "updatePkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updatePkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updatePkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.PkoViewSDO updatePkoView1(@WebParam(mode = WebParam.Mode.IN, name = "pkoView1")
                                                         ua.divas.service.vo.common.PkoViewSDO pkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/deletePkoView1", operationName = "deletePkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "deletePkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "deletePkoView1Response")
    void deletePkoView1(@WebParam(mode = WebParam.Mode.IN, name = "pkoView1")
                        ua.divas.service.vo.common.PkoViewSDO pkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/mergePkoView1", operationName = "mergePkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergePkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergePkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.PkoViewSDO mergePkoView1(@WebParam(mode = WebParam.Mode.IN, name = "pkoView1")
                                                        ua.divas.service.vo.common.PkoViewSDO pkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findPkoView1", operationName = "findPkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findPkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findPkoView1Response")
    @WebResult(name = "result")
    List<ua.divas.service.vo.common.PkoViewSDO> findPkoView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                             FindCriteria findCriteria,
                                                             @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                             FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getRkoView1", operationName = "getRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getRkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.RkoViewSDO getRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                                      String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/createRkoView1", operationName = "createRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createRkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.RkoViewSDO createRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "rkoView1")
                                                         ua.divas.service.vo.common.RkoViewSDO rkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/updateRkoView1", operationName = "updateRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "updateRkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.RkoViewSDO updateRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "rkoView1")
                                                         ua.divas.service.vo.common.RkoViewSDO rkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/deleteRkoView1", operationName = "deleteRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "deleteRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "deleteRkoView1Response")
    void deleteRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "rkoView1")
                        ua.divas.service.vo.common.RkoViewSDO rkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/mergeRkoView1", operationName = "mergeRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergeRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "mergeRkoView1Response")
    @WebResult(name = "result")
    ua.divas.service.vo.common.RkoViewSDO mergeRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "rkoView1")
                                                        ua.divas.service.vo.common.RkoViewSDO rkoView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findRkoView1", operationName = "findRkoView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findRkoView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findRkoView1Response")
    @WebResult(name = "result")
    List<ua.divas.service.vo.common.RkoViewSDO> findRkoView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                             FindCriteria findCriteria,
                                                             @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                             FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getUserSettingsView1", operationName = "getUserSettingsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getUserSettingsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getUserSettingsView1Response")
    @WebResult(name = "result")
    UserSettingsViewSDO getUserSettingsView1(@WebParam(mode = WebParam.Mode.IN, name = "id")
                                             String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findUserSettingsView1", operationName = "findUserSettingsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findUserSettingsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findUserSettingsView1Response")
    @WebResult(name = "result")
    List<UserSettingsViewSDO> findUserSettingsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;


    @WebMethod(action = "/ua/divas/service/app/common/findUsersView1", operationName = "findUsersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findUsersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findUsersView1Response")
    @WebResult(name = "result")
    List<UsersViewSDO> findUsersView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                      FindCriteria findCriteria,
                                      @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                      FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findGroupmembersView1", operationName = "findGroupmembersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findGroupmembersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findGroupmembersView1Response")
    @WebResult(name = "result")
    List<GroupmembersViewSDO> findGroupmembersView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getKassaSettingsView1", operationName = "getKassaSettingsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getKassaSettingsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "getKassaSettingsView1Response")
    @WebResult(name = "result")
    KassaSettingsViewSDO getKassaSettingsView1() throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/findNomenklaturaView1", operationName = "findNomenklaturaView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findNomenklaturaView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/",
                     localName = "findNomenklaturaView1Response")
    @WebResult(name = "result")
    List<NomenklaturaViewSDO> findNomenklaturaView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                    FindCriteria findCriteria,
                                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getOrderStatusView1", operationName = "getOrderStatusView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOrderStatusView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOrderStatusView1Response")
    @WebResult(name = "result")
    OrderStatusViewSDO getOrderStatusView1() throws ServiceException;


    @WebMethod(action = "/ua/divas/service/app/common/findNomGroup1", operationName = "findNomGroup1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findNomGroup1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "findNomGroup1Response")
    @WebResult(name = "result")
    List<NomGroupSDO> findNomGroup1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria") FindCriteria findCriteria,
                                    @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                    FindControl findControl) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getKontragentsView1", operationName = "getKontragentsView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getKontragentsView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getKontragentsView1Response")
    @WebResult(name = "result")
    KontragentsViewSDO getKontragentsView1() throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getOrdersView1", operationName = "getOrdersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOrdersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getOrdersView1Response")
    @WebResult(name = "result")
    OrdersViewSDO getOrdersView1(@WebParam(mode = WebParam.Mode.IN, name = "id") String id) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/createOrdersView1", operationName = "createOrdersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createOrdersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "createOrdersView1Response")
    @WebResult(name = "result")
    OrdersViewSDO createOrdersView1(@WebParam(mode = WebParam.Mode.IN, name = "ordersView1")
                                    OrdersViewSDO ordersView1) throws ServiceException;

    @WebMethod(action = "/ua/divas/service/app/common/getUsersView1", operationName = "getUsersView1")
    @RequestWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getUsersView1")
    @ResponseWrapper(targetNamespace = "/ua/divas/service/app/common/types/", localName = "getUsersView1Response")
    @WebResult(name = "result")
    UsersViewSDO getUsersView1() throws ServiceException;
}

